# Generated by Django 5.2 on 2025-12-19 00:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Nome da Sala")),
                ("is_private", models.BooleanField(default=False, verbose_name="Sala Privada")),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="rooms", to=settings.AUTH_USER_MODEL, verbose_name="Participantes"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sala",
                "verbose_name_plural": "Salas",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField(verbose_name="Conteúdo")),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pendente"), ("APPROVED", "Aprovada"), ("REJECTED", "Rejeitada")],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.room",
                        verbose_name="Sala",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem",
                "verbose_name_plural": "Mensagens",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["name"], name="chat_room_name_8fdd04_idx"),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["is_private", "created_at"], name="chat_room_is_priv_0eb112_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["room", "status", "created_at"], name="chat_messag_room_id_f19d29_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["author", "created_at"], name="chat_messag_author__95f2a5_idx"),
        ),
    ]
