# Generated by Django 5.2 on 2025-12-19 02:34

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomParticipant",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("ADMIN", "Administrador"), ("MEMBER", "Membro")],
                        default="MEMBER",
                        max_length=20,
                        verbose_name="Função",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="chat.room"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Participante da Sala",
                "verbose_name_plural": "Participantes da Sala",
            },
        ),
        migrations.AlterField(
            model_name="room",
            name="participants",
            field=models.ManyToManyField(
                related_name="rooms",
                through="chat.RoomParticipant",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Participantes",
            ),
        ),
        migrations.AddIndex(
            model_name="roomparticipant",
            index=models.Index(fields=["room", "role"], name="chat_roompa_room_id_bc2478_idx"),
        ),
        migrations.AddIndex(
            model_name="roomparticipant",
            index=models.Index(fields=["user", "role"], name="chat_roompa_user_id_cfdb5e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="roomparticipant",
            unique_together={("room", "user")},
        ),
    ]
