# Generated by Django 5.2 on 2025-12-19 03:23

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModerationLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        help_text="Ex: local_dictionary, openai, azure", max_length=50, verbose_name="Provedor"
                    ),
                ),
                (
                    "verdict",
                    models.CharField(help_text="Ex: APPROVED, REJECTED", max_length=20, verbose_name="Veredicto"),
                ),
                (
                    "score",
                    models.FloatField(blank=True, help_text="0.0 a 1.0", null=True, verbose_name="Score de Confiança"),
                ),
                (
                    "raw_payload",
                    models.JSONField(default=dict, help_text="Resposta completa", verbose_name="Payload Bruto"),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_logs",
                        to="chat.message",
                        verbose_name="Mensagem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Moderação",
                "verbose_name_plural": "Logs de Moderação",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["message", "created_at"], name="moderation__message_c37346_idx"),
                    models.Index(fields=["provider", "verdict"], name="moderation__provide_e190cf_idx"),
                ],
            },
        ),
    ]
